### ISSUE TITLE
IP logger always returns 172.18.0.1

### ISSUE THREAD

**Issue by eesazahed** [TheRedstoneRadiant/Qurl.gq#26]
172.18.0.1 (which is a private IP) is always returned. Perhaps it has to do with the API for getting IPs? Or whichever site is hosting qurl.gq?

![Screen Shot 2022-10-12 at 4 51 27 PM](https://user-images.githubusercontent.com/97064249/195445314-145c28f7-ed47-4801-bd6b-478d6e6719eb.png)

**Comment by TheRedstoneRadiant** [comment]
I believe this is due to line 29 under [router/shortUrl.js](https://github.com/TheRedstoneRadiant/Qurl.gq/blob/a595eb836f4af460cf7eb72d36bf0b979842aa60/router/shortUrl.js#L29)

```js
    let ipAddress = req.socket.remoteAddress || req.headers["x-forwarded-for"] || "";
```

I believe this is because `req.socket.remoteAddress` is being preferred over the `x-forwarded-for` header.
The statement should be reversed.
